receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      load: {}
      network: {}
      paging: {}
      processes: {}
#      system: {}

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s

  memory_limiter:
    check_interval: 5s
    limit_mib: 512
    spike_limit_mib: 128

  resource/metrics:
    attributes:
      - action: insert
        key: service.name
        value: "otel-gateway"
      - action: insert
        key: host.name
        value: "otel-gateway-host"
      - action: insert
        key: host.id
        value: "otel-gateway-host"
  resource/traces:
    attributes:
      - action: insert
        key: deployment.environment
        value: "lab"
  resourcedetection:
    detectors: [system, gcp]
    override: false
exporters:
# ðŸ”¹ Splunk Observability
#  otlphttp/splunk:
#    endpoint: https://ingest.sg0.signalfx.com/v2/otlp
#    headers:
#      X-SF-TOKEN: "LFpIZu-TGRc76mCZozr8zgy"

  # ðŸ”¹ Jaeger (local)
#  otlp/jaeger:
#    endpoint: jaeger:4317
#    tls:
#      insecure: true

  signalfx:
    access_token: "kod78aTll04E-ATMzlUYoA"
    ingest_url: "https://ingest.sg0.signalfx.com"
    api_url: "https://api.sg0.signalfx.com"
    sync_host_metadata: true

  otlp:
    endpoint: ingest.sg0.signalfx.com:443
    headers:
     X-SF-TOKEN: "kod78aTll04E-ATMzlUYoA"

    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 4000

    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [memory_limiter,resourcedetection,resource/metrics, batch]
      exporters: [signalfx,debug]

    traces:
      receivers: [otlp]
      processors: [memory_limiter,resource/traces, batch]
      exporters: [otlp]

    logs:
      receivers: [otlp]
      processors: [memory_limiter,batch]
      exporters: [debug]

