- name: Copy otel agent config
  copy:
    src: otel-gateway.yml
    dest: "{{ otel_base_dir }}/configs/otel-gateway/otel-gateway.yml"
    mode: '0644'
  notify: restart otel gateway
- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: "{{ otel_base_dir }}/docker-compose/otel-gateway/docker-compose.yml"
    mode: '0644'
  notify: restart otel gateway
