- name: start splunk agent
  command: docker compose up -d
  args:
    chdir: "{{ splunk_base_dir }}/docker-compose"

- name: restart splunk agent
  command: docker compose restart
  args:
    chdir: "{{ splunk_base_dir }}/docker-compose"
