- name: start prom agent
  command: docker compose up -d
  args:
    chdir: "{{ prom_base_dir }}/docker-compose"

- name: restart prom agent
  command: docker compose restart
  args:
    chdir: "{{ prom_base_dir }}/docker-compose"
